name: se7ety_eraa_16_11
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
